version: '3.6'
services:
  gitlab: # https://docs.gitlab.cn/jh/install/docker.html
    image: 'registry.gitlab.cn/omnibus/gitlab-jh:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
  nginx: # https://hub.docker.com/_/nginx?tab=tags
    image: nginx
    ports:
    - "8090:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
  jenkins: # https://juejin.cn/post/7063840085950595108
    image: jenkins/jenkins:lts
    restart: always
    ports:
    - "8080:8080"
    expose:  # 暴露端口
      - "8080"
      - "50000"
  nexus: # https://juejin.cn/post/7063840085950595108
    image: sonatype/nexus3
    restart: always
    ports:
    - "8081:8081"
    expose:  # 暴露端口
      - "8081"